spring.application.name=HospitalManagement

spring.datasource.url=jdbc:mariadb://localhost:3306/app
spring.datasource.username=root
spring.datasource.password=1@Peterear

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
